import type { AIModel } from '../types';

const MODELS: AIModel[] = [
  // ─── SCRIPT ───────────────────────────────────────────────
  {
    id: 'qwen2.5-7b-local',
    name: 'Qwen 2.5 7B (Local)',
    provider: 'local',
    type: 'script',
    description: '7B instruct model via Ollama. Excellent UGC copy quality. Runs on any M-series Mac.',
    quality: 'high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'ollama', 'recommended'],
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout (Local)',
    provider: 'local',
    type: 'script',
    description: 'Runs Qwen 2.5 7B via Ollama on M-series Mac. Apache 2.0.',
    quality: 'high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'ollama'],
  },
  {
    id: 'mistral-small-4',
    name: 'Mistral Small 4 (Local)',
    provider: 'local',
    type: 'script',
    description: 'Runs Qwen 2.5 7B via Ollama. Good for short-form UGC scripts.',
    quality: 'high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'ollama'],
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    type: 'script',
    description: 'Best reasoning + 200K context. Unmatched for nuanced UGC copy.',
    quality: 'highest',
    pricing: '$5 / 1M tokens',
    available: false,
    tags: ['best-quality', 'long-form'],
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xai',
    type: 'script',
    description: 'xAI flagship model. Requires XAI_API_KEY.',
    quality: 'highest',
    pricing: 'Pay per token',
    available: false,
    tags: ['xai', 'api'],
  },

  // ─── IMAGE ────────────────────────────────────────────────
  {
    id: 'flux-schnell-local',
    name: 'FLUX.1-Schnell (Local)',
    provider: 'local',
    type: 'image',
    description: 'FLUX.1-Schnell Q4 via mflux (Apple Silicon MLX). 4-step generation. ~15-30s per image. Apache 2.0.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'mflux', 'recommended', 'apple-silicon'],
  },
  {
    id: 'flux-dev-local',
    name: 'FLUX.1-Dev (Local)',
    provider: 'local',
    type: 'image',
    description: 'FLUX.1-Dev Q4 via mflux. Higher quality, 20+ steps. Slower than Schnell.',
    quality: 'highest',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'mflux', 'apple-silicon'],
  },
  {
    id: 'flux-2-pro',
    name: 'FLUX 2 Pro',
    provider: 'blackforestlabs',
    type: 'image',
    description: '#1 photorealism. 4.5s generation. Best for product & cinematic shots.',
    quality: 'highest',
    pricing: '$0.055 / image',
    available: false,
    tags: ['photorealism', 'product'],
  },
  {
    id: 'midjourney-v8',
    name: 'Midjourney v8',
    provider: 'midjourney',
    type: 'image',
    description: 'Native 2K, 5× faster. Used by 61% of pro designers. Best aesthetic control.',
    quality: 'highest',
    pricing: '$10 / mo',
    available: false,
    tags: ['artistic', 'aesthetic'],
  },
  {
    id: 'gpt-image-1-5',
    name: 'GPT Image 1.5',
    provider: 'openai',
    type: 'image',
    description: 'Best prompt comprehension. Understands complex multi-object compositions.',
    quality: 'highest',
    pricing: '$0.04 / image',
    available: false,
    tags: ['prompt-following', 'versatile'],
  },

  // ─── VOICE ────────────────────────────────────────────────
  {
    id: 'kokoro-82m-local',
    name: 'Kokoro 82M (Local)',
    provider: 'local',
    type: 'voice',
    description: '82M param TTS via kokoro-onnx. Real-time on CPU, fast on MPS. Apache 2.0. Multiple voice styles.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'fast', 'apache', 'recommended'],
  },
  {
    id: 'cosyvoice-2-local',
    name: 'CosyVoice 2 (Local)',
    provider: 'local',
    type: 'voice',
    description: 'Also routes via Kokoro 82M locally. Same high quality.',
    quality: 'high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'streaming'],
  },
  {
    id: 'fish-audio-s2',
    name: 'Fish Audio S2',
    provider: 'fishaudio',
    type: 'voice',
    description: 'ELO #1 on Speech Arena. 80+ languages, 50+ emotions. 15-sec voice clone.',
    quality: 'highest',
    pricing: '$15 / 1M chars',
    available: false,
    tags: ['multilingual', 'voice-clone', 'top-ranked'],
  },
  {
    id: 'elevenlabs-turbo-v3',
    name: 'ElevenLabs Turbo v3',
    provider: 'elevenlabs',
    type: 'voice',
    description: 'Industry standard. Ultra-low latency. Best for professional narration.',
    quality: 'very-high',
    pricing: '$60–165 / 1M chars',
    available: false,
    tags: ['professional', 'low-latency'],
  },

  // ─── VIDEO ────────────────────────────────────────────────
  {
    id: 'ltx-2-3-local',
    name: 'Ken Burns + Voice (Local)',
    provider: 'local',
    type: 'video',
    description: 'Assembles AI image + voice-over into a smooth cinematic video using Ken Burns zoom. Uses ffmpeg — instant generation, no GPU needed.',
    quality: 'high',
    pricing: 'Free (local)',
    available: true,
    tags: ['local', 'ffmpeg', 'recommended', 'instant'],
  },
  {
    id: 'runway-gen-4-5',
    name: 'Runway Gen-4.5',
    provider: 'runway',
    type: 'video',
    description: 'Ranked #1 Artificial Analysis benchmark. Best for UGC short-form clips.',
    quality: 'highest',
    pricing: '$0.25 / sec',
    available: false,
    tags: ['top-ranked', 'ugc'],
  },
  {
    id: 'veo-3-1',
    name: 'Veo 3.1',
    provider: 'google',
    type: 'video',
    description: 'Tops T2V + I2V leaderboards. Generates audio alongside video.',
    quality: 'highest',
    pricing: '$0.05–0.40 / sec',
    available: false,
    tags: ['audio-included', 'i2v', 't2v'],
  },
  {
    id: 'grok-imagine-video',
    name: 'Grok Imagine Video',
    provider: 'xai',
    type: 'video',
    description: 'Launched April 2026. Arena score 724. Available via OpenRouter.',
    quality: 'high',
    pricing: '$0.02 / sec',
    available: false,
    tags: ['budget', 'openrouter'],
  },
];

export function getModelsByType(type: AIModel['type']): AIModel[] {
  return MODELS.filter(m => m.type === type);
}

export function getModelById(id: string): AIModel | undefined {
  return MODELS.find(m => m.id === id);
}

export function getAllModels(): AIModel[] {
  return MODELS;
}
