import type { AIModel } from '../types';

const MODELS: AIModel[] = [
  // ─── SCRIPT ───────────────────────────────────────────────
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    type: 'script',
    description: 'Best reasoning + 200K context. Unmatched for nuanced UGC copy.',
    quality: 'highest',
    pricing: '$5 / 1M tokens',
    available: false,
    tags: ['best-quality', 'long-form'],
  },
  {
    id: 'gpt-5-5',
    name: 'GPT-5.5',
    provider: 'openai',
    type: 'script',
    description: 'Fastest inference. Leads GPQA & SWE-Bench. Great for quick drafts.',
    quality: 'highest',
    pricing: '$2.50 / 1M tokens',
    available: false,
    tags: ['fast', 'versatile'],
  },
  {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    type: 'script',
    description: '200K context, 61% cheaper than Claude with minimal quality drop.',
    quality: 'very-high',
    pricing: '$2 / 1M tokens',
    available: false,
    tags: ['budget', 'long-context'],
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout (Local)',
    provider: 'local',
    type: 'script',
    description: '17B MoE via Ollama. Runs on RTX 3060 8GB. Apache 2.0.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: false,
    tags: ['local', 'ollama'],
  },
  {
    id: 'mistral-small-4',
    name: 'Mistral Small 4 (Local)',
    provider: 'local',
    type: 'script',
    description: '119B MoE (~6B active). Q4 quantized. Dual 4090 or M-series Mac.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: false,
    tags: ['local', 'ollama'],
  },

  // ─── IMAGE ────────────────────────────────────────────────
  {
    id: 'flux-2-pro',
    name: 'FLUX 2 Pro',
    provider: 'blackforestlabs',
    type: 'image',
    description: '#1 photorealism. 4.5s generation. Best for product & cinematic shots.',
    quality: 'highest',
    pricing: '$0.055 / image',
    available: false,
    tags: ['photorealism', 'product'],
  },
  {
    id: 'midjourney-v8',
    name: 'Midjourney v8',
    provider: 'midjourney',
    type: 'image',
    description: 'Native 2K, 5× faster. Used by 61% of pro designers. Best aesthetic control.',
    quality: 'highest',
    pricing: '$10 / mo',
    available: false,
    tags: ['artistic', 'aesthetic'],
  },
  {
    id: 'gpt-image-1-5',
    name: 'GPT Image 1.5',
    provider: 'openai',
    type: 'image',
    description: 'Best prompt comprehension. Understands complex multi-object compositions.',
    quality: 'highest',
    pricing: '$0.04 / image',
    available: false,
    tags: ['prompt-following', 'versatile'],
  },
  {
    id: 'imagen-4-fast',
    name: 'Imagen 4 Fast',
    provider: 'google',
    type: 'image',
    description: '2K resolution at $0.02/img. Best budget-to-quality ratio for volume work.',
    quality: 'high',
    pricing: '$0.02 / image',
    available: false,
    tags: ['budget', 'fast'],
  },
  {
    id: 'ideogram-v3',
    name: 'Ideogram V3',
    provider: 'ideogram',
    type: 'image',
    description: 'Only model with 90–95% text-in-image accuracy. For logos & captions.',
    quality: 'high',
    pricing: '$0.03 / image',
    available: false,
    tags: ['text-in-image', 'specialized'],
  },
  {
    id: 'flux-dev-local',
    name: 'FLUX.1 Dev (Local)',
    provider: 'local',
    type: 'image',
    description: 'High-quality open-weights. Runs via ComfyUI on RTX 3090+.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: false,
    tags: ['local', 'comfyui'],
  },

  // ─── VOICE ────────────────────────────────────────────────
  {
    id: 'fish-audio-s2',
    name: 'Fish Audio S2',
    provider: 'fishaudio',
    type: 'voice',
    description: 'ELO #1 on Speech Arena. 80+ languages, 50+ emotions. 15-sec voice clone.',
    quality: 'highest',
    pricing: '$15 / 1M chars',
    available: false,
    tags: ['multilingual', 'voice-clone', 'top-ranked'],
  },
  {
    id: 'elevenlabs-turbo-v3',
    name: 'ElevenLabs Turbo v3',
    provider: 'elevenlabs',
    type: 'voice',
    description: 'Industry standard. Ultra-low latency. Best for professional narration.',
    quality: 'very-high',
    pricing: '$60–165 / 1M chars',
    available: false,
    tags: ['professional', 'low-latency'],
  },
  {
    id: 'openai-tts-hd',
    name: 'OpenAI TTS HD',
    provider: 'openai',
    type: 'voice',
    description: 'Clean, natural speech. 6 built-in voices. Fast API response.',
    quality: 'high',
    pricing: '$30 / 1M chars',
    available: false,
    tags: ['simple', 'reliable'],
  },
  {
    id: 'kokoro-82m-local',
    name: 'Kokoro 82M (Local)',
    provider: 'local',
    type: 'voice',
    description: '210× real-time on GPU, 3–11× on CPU. Apache 2.0. Zero recurring cost.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: false,
    tags: ['local', 'fast', 'apache'],
  },
  {
    id: 'cosyvoice-2-local',
    name: 'CosyVoice 2 (Local)',
    provider: 'local',
    type: 'voice',
    description: '150ms streaming latency. Lightweight FastAPI deployment.',
    quality: 'high',
    pricing: 'Free (local)',
    available: false,
    tags: ['local', 'streaming'],
  },

  // ─── VIDEO ────────────────────────────────────────────────
  {
    id: 'runway-gen-4-5',
    name: 'Runway Gen-4.5',
    provider: 'runway',
    type: 'video',
    description: 'Ranked #1 Artificial Analysis benchmark. Best for UGC short-form clips.',
    quality: 'highest',
    pricing: '$0.25 / sec',
    available: false,
    tags: ['top-ranked', 'ugc'],
  },
  {
    id: 'veo-3-1',
    name: 'Veo 3.1',
    provider: 'google',
    type: 'video',
    description: 'Tops T2V + I2V leaderboards. Generates audio alongside video.',
    quality: 'highest',
    pricing: '$0.05–0.40 / sec',
    available: false,
    tags: ['audio-included', 'i2v', 't2v'],
  },
  {
    id: 'ltx-2-3-local',
    name: 'LTX-2.3 Fast (Local)',
    provider: 'local',
    type: 'video',
    description: 'Best open-weights T2V (ELO 974). 27B MoE. RTX 4090 24GB. Apache 2.0.',
    quality: 'very-high',
    pricing: 'Free (local)',
    available: false,
    tags: ['local', 'open-weights'],
  },
  {
    id: 'grok-imagine-video',
    name: 'Grok Imagine Video',
    provider: 'xai',
    type: 'video',
    description: 'Launched April 2026. Arena score 724. Available via OpenRouter.',
    quality: 'high',
    pricing: '$0.02 / sec',
    available: false,
    tags: ['budget', 'openrouter'],
  },
];

export function getModelsByType(type: AIModel['type']): AIModel[] {
  return MODELS.filter(m => m.type === type);
}

export function getModelById(id: string): AIModel | undefined {
  return MODELS.find(m => m.id === id);
}

export function getAllModels(): AIModel[] {
  return MODELS;
}
